FROM postgres:alpine
MAINTAINER James Vasile <james@opentechstrategies.com>
#RUN su postgres -c 'pg_ctl -D "/var/lib/postgresql/data" -m fast -w stop' &&\
#    psql --command "CREATE USER psm WITH PASSWORD 'psm';" &&\
#    createdb -O psm psm

EXPOSE 5432
