ALTER SEQUENCE MITA3_SEQ INCREMENT BY 100;
SELECT MITA3_SEQ.NEXTVAL from DUAL;
ALTER SEQUENCE MITA3_SEQ INCREMENT BY 1;

INSERT INTO ROLE (ROLE_ID, NAME) VALUES (1, 'Provider');
INSERT INTO ROLE (ROLE_ID, NAME) VALUES (2, 'Service Agent');
INSERT INTO ROLE (ROLE_ID, NAME) VALUES (3, 'Service Administrator');
INSERT INTO ROLE (ROLE_ID, NAME) VALUES (4, 'System Administrator');

INSERT INTO USER_STATUS (USER_STATUS_ID, NAME) VALUES (1, 'Active');
INSERT INTO USER_STATUS (USER_STATUS_ID, NAME) VALUES (2, 'Inactive');

INSERT INTO PROVIDER_TYPE (PROVIDER_TYPE_ID, NAME, PRIVATE_OFFICE_IND, EMPLOYED_CONTRACTED_IND, ADDITONAL_PRACTICE_IND, PAYMENT_REQUIRED_IND) 
   VALUES (1, 'provider type 1', 1, 1, 0, 1);
INSERT INTO PROVIDER_TYPE (PROVIDER_TYPE_ID, NAME, PRIVATE_OFFICE_IND, EMPLOYED_CONTRACTED_IND, ADDITONAL_PRACTICE_IND, PAYMENT_REQUIRED_IND) 
   VALUES (2, 'provider type 2', 0, 0, 0, 0);

INSERT INTO ADDRESS (ADDRESS_ID, LINE_1, CITY, STATE, ZIPCODE, COUNTY) 
   VALUES (1, 'location 1', 'city 1', 'MN', '12345', '');

INSERT INTO PRIVATE_PRACTICE (PRIVATE_PRACTICE_ID, NAME, GROUP_NPI, OFFICE_PHONE_NUMBER, OFFICE_FAX_NUMBER,
    LEGAL_NAME, FEDERAL_TAX_ID, STATE_TAX_ID, CREATED_BY, CREATE_TIME,
    MODIFIED_BY, MODIFIED_TIME, OFFICE_ADDRESS_ID, BILLING_ADDRESS_ID) 
   VALUES (1, 'practice name 1', 'group npi 1', '(111) 111-1111', null, 
       'legal name 1', 'fed tax id 1', 'state tax id 1', 'SYSTEM', SYSDATE,
       null, null, 1, null);

INSERT INTO PROVIDER_STATEMENT (PROVIDER_STATEMENT_ID, NAME, TITLE, STATEMENT_DATE,
    CREATED_BY, CREATE_TIME, MODIFIED_BY, MODIFIED_TIME, SIGNATURE) 
   VALUES (1, 'statement name 1', 'statement title 1', SYSDATE, 
       'SYSTEM', SYSDATE, null, null, empty_blob());

INSERT INTO ENROLLMENT_STATUS (ENROLLMENT_STATUS_ID, NAME) VALUES (1, 'Pending');
INSERT INTO ENROLLMENT_STATUS (ENROLLMENT_STATUS_ID, NAME) VALUES (2, 'Denied');
INSERT INTO ENROLLMENT_STATUS (ENROLLMENT_STATUS_ID, NAME) VALUES (3, 'Approved');

INSERT INTO REQUEST_TYPE (REQUEST_TYPE_ID, NAME) VALUES (1, 'request type 1');
INSERT INTO REQUEST_TYPE (REQUEST_TYPE_ID, NAME) VALUES (2, 'request type 2');
    
INSERT INTO ENROLLMENT (ENROLLMENT_ID, START_DT, END_DT, DENIAL_REASON, CREATED_BY, 
    CREATE_TIME, MODIFIED_BY, MODIFIED_TIME, ENROLLMENT_STATUS_ID, 
    REQUEST_TYPE_ID, USER_ID, APPEAL_ID, PROCESS_INSTANCE_ID)
    VALUES (1, to_date('2012/07/09', 'yyyy/mm/dd'), to_date('2015/07/09', 'yyyy/mm/dd'), null, 'SYSTEM',
        SYSDATE, null, null, 1, 1, null, null, 1);
       
INSERT INTO PROVIDER_PROFILE (PROVIDER_PROFILE_ID, SSN, DOB, REQUEST_EFFECTIVE_DT, DEGREE, 
    DEGREE_AWARD_DT, PRIVATE_OFFICE_IND, REMITTANCE_EMAIL_PREF, REIMBURSEMENT_EMAIL_PREF, 
    CORRESPONDENCE_EMAIL_PREF, AUTHORIZATION_EMAIL_PREF, ENROLLMENT_EMAIL_PREF, REMITTANCE_SEQ_ORDER, CRIMINAL_CONVICTION_IND, 
    CIVIL_PENALTY_IND, TERMINATED_IND, CONTACT_NAME, CONTACT_PHONE_NUMBER, CONTACT_FAX_NUMBER,
    CONTACT_EMAIL, FINGERPRINT_SCANNED_FILE, SCANNED_EFT_FORM, ENROLLMENT_FEE_REQUIRED_IND, ENROLLMENT_FEE,
    ENROLLMENT_FEE_PAID_IND, NPI, PROVIDER_AGREEMENT_FILE, PRIMARY_TAXONOMY, PREFIX,
    SUFFIX, CREDENTIALS, OTHER_PREFIX, OTHER_SUFFIX, OTHER_FIRST_NAME,
    OTHER_MIDDLE_NAME, OTHER_LAST_NAME, ZIP_LUMP_SUM, DATE_OF_DEATH, SSN_VERIFIED_IND,
    EMPLOYER_ID, ALIAS, ACTION_FROM_DT, ACTION_TO_DT, TERMINATION_FROM_DT,
    TERMINATION_TO_DT, CREATE_FROM_DT, CREATE_TO_DT, MODIFY_FROM_DT, MODIFY_TO_DT,
    RECIPROCAL_CD, PROCUREMENT_CD, AGENCY, DUNS, CAGE_CODE,
    DBA, SEX, NAME, CREATED_BY, CREATE_TIME,
    MODIFIED_BY, MODIFIED_TIME, PROVIDER_TYPE_ID, PRIVATE_PRACTICE_ID, 
    PROVIDER_STATEMENT_ID, CURRENT_ENROLLMENT_ID, PREVIOUS_ENROLLMENT_ID, MAJOR_PROGRAM_ID, 
    CATEGORY_SVC_ID, COMPLAINT_TYPE_ID, EXCLUSION_TYPE_ID, RISK_LEVEL_ID, BUSINESS_ID)
    VALUES (1, '111111111', to_date('1975/07/09', 'yyyy/mm/dd'), to_date('2012/07/09', 'yyyy/mm/dd'), 1,
        to_date('2003/07/09', 'yyyy/mm/dd'), 1, 0, 0,
        0, 0, 0, 0, 0,
        0, 0, 'contact name 1', '(111)111-1111 ext 1111', '(111)111-1111', 
        'contact1@cms.gov', '', '', 1, 250, 
        1, 11111111, 'agreement file 1', 'taxonomy 1', 'prefix 1',
        'suffix 1', 'credentials 1', 'other prefix 1', 'other suffix 1', 'other first 1',
        'other middle 1', 'other last 1', 'zip lump sum 1', null, 0, 
        'employer id 1', 'alias 1', null, null, null,
        null, null, null, null, null,
        'reciprocal 1', 'procurement 1', 'agency 1', 111111111, 'cage code 1',
        'dba 1', 0, 'name 1', 'SYSTEM', SYSDATE, 
        null, null, 1, 1, 
        1, 1, null, null,
        null, null, null, null, null
    );  

INSERT INTO PROVIDER_PROFILE_ADDRESS (PROVIDER_PROFILE_ID, ADDRESS_ID) VALUES(1, 1);


INSERT INTO CMS_USER (USER_ID, USERNAME, EMAIL, FIRST_NAME, LAST_NAME, MIDDLE_NAME, PROVIDER_PROFILE_ID, ROLE_ID, STATUS_ID)
    VALUES(1, 'user1', 'user1@cms.gov', 'first1', 'last1', 'middle1', 1, 1, 1);
    
INSERT INTO SCREENING_SCHEDULE (SCREENING_SCHEDULE_ID, UPCOMING_SCREENING_DT, INTERVAL, INTERVAL_TYPE)
    VALUES(1, to_date('2020/01/01', 'yyyy/mm/dd'), 1, 1);


INSERT INTO NOTIFICATION_TYPE (NOTIFICATION_TYPE_ID, NAME) VALUES(1, 'Test Notification');
INSERT INTO NOTIFICATION_TEMPLATE (NOTIFICATION_TEMPLATE_ID, NOTIFICATION_TYPE_ID, TEMPLATE_FILE) VALUES(1, 1, 'email_template.txt');

INSERT INTO LICENSE_TYPE (LICENSE_TYPE_ID, NAME) VALUES(1, 'License Type 1');
INSERT INTO LICENSE_TYPE (LICENSE_TYPE_ID, NAME) VALUES(2, 'License Type 2');

INSERT INTO LICENSE (LICENSE_ID, DESCRIPTION, LICENSE_NUMBER, ORIGINAL_ISSUE_DT, RENEWAL_END_DT,
    ISSUING_US_STATE, PERMIT_NUMBER, PASSWORD, STATUS_DT, DISCIPLINE,
    CORRECTIVE_ACTION, EXPIRE_DT, LICENSE_TYPE_ID, LICENSE_LEVEL_ID, PROVIDER_PROFILE_ID) 
    VALUES(1, 'Specialty 1', '111111111', to_date('2011/01/01', 'yyyy/mm/dd'), to_date('2015/01/01', 'yyyy/mm/dd'),
        'MN', '11111111', NULL, NULL, 0, 
        0, to_date('2015/01/01', 'yyyy/mm/dd'), 1, NULL, NULL);
    
INSERT INTO LICENSE (LICENSE_ID, DESCRIPTION, LICENSE_NUMBER, ORIGINAL_ISSUE_DT, RENEWAL_END_DT,
    ISSUING_US_STATE, PERMIT_NUMBER, PASSWORD, STATUS_DT, DISCIPLINE,
    CORRECTIVE_ACTION, EXPIRE_DT, LICENSE_TYPE_ID, LICENSE_LEVEL_ID, PROVIDER_PROFILE_ID) 
    VALUES(2, 'Specialty 2', '22222222', to_date('2011/02/02', 'yyyy/mm/dd'), to_date('2015/02/02', 'yyyy/mm/dd'),
        'NY', '22222222', NULL, NULL, 0, 
        0, to_date('2015/02/02', 'yyyy/mm/dd'), 2, NULL, NULL);
    
INSERT INTO PROVIDER_PROFILE_LICENSE (PROVIDER_PROFILE_ID, LICENSE_ID) VALUES(1, 1);
INSERT INTO PROVIDER_PROFILE_LICENSE (PROVIDER_PROFILE_ID, LICENSE_ID) VALUES(1, 2);

INSERT INTO SPECIALTY_TYPE (SPECIALTY_TYPE_ID, NAME) VALUES(1, 'Specialty Type');
INSERT INTO SPECIALTY (SPECIALTY_ID, NAME, CODE, SPECIALTY_TYPE_ID) VALUES(1, 'Specialty', 123456, 1);

INSERT INTO MAJOR_PROGRAM (MAJOR_PROGRAM_ID, NAME) VALUES(1, 'Major Major');

INSERT INTO CATEGORY_SVC (CATEGORY_SVC_ID, NAME) VALUES(1, 'Category Service');

INSERT INTO TRIBAL_CD (TRIBAL_CD_ID, NAME) VALUES(1, 'Tribal Code');

INSERT INTO RISK_LEVEL (RISK_LEVEL_ID, NAME) VALUES(1, 'Risk Level');

INSERT INTO EXCLUSION_TYPE (EXCLUSION_TYPE_ID, NAME) VALUES(1, 'Exclusion Type');

INSERT INTO COMPLAINT_TYPE (COMPLAINT_TYPE_ID, NAME) VALUES(1, 'Complaint Type');

INSERT INTO REQUIRED_FLD_TYPE (REQUIRED_FLD_TYPE_ID, NAME) VALUES(1, 'Required Field Type');

INSERT INTO REQUIRED_FLD (REQUIRED_FLD_ID, NAME, REQUIRED_FLD_TYPE_ID) VALUES(1, 'Required Field', 1);

INSERT INTO LICENSE_LEVEL (LICENSE_LEVEL_ID, NAME) VALUES(1, 'License Level');

INSERT INTO PERMIT_TYPE (PERMIT_TYPE_ID, NAME) VALUES(1, 'Permit Type');

INSERT INTO FILE_FMT (FILE_FMT_ID, NAME) VALUES(1, 'File Format');