SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DEATH_MASTER_RECORD`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`DEATH_MASTER_RECORD` (
  `ID` BIGINT NOT NULL ,
  `SSN` VARCHAR(9) NOT NULL ,
  `LAST_NAME` VARCHAR(20) NOT NULL ,
  `NAME_SUFFIX` VARCHAR(4) NOT NULL ,
  `FIRST_NAME` VARCHAR(15) NOT NULL ,
  `MIDDLE_NAME` VARCHAR(15) NOT NULL ,
  `VP_CODE` VARCHAR(1) NOT NULL ,
  `DATE_OF_DEATH` DATE NOT NULL ,
  `DATE_OF_BIRTH` DATE NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `SSN_INDEX` (`SSN` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PECOS_RECORD`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`PECOS_RECORD` (
  `ID` BIGINT NOT NULL ,
  `NPI` VARCHAR(50) NOT NULL ,
  `LAST_NAME` VARCHAR(50) NOT NULL ,
  `FIRST_NAME` VARCHAR(50) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `NPI_INDEX` (`NPI` ASC) )
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
