-- added 2/22/13 - categorize beneficial owner types A-ALL, P - Person, O - Organization
ALTER TABLE LU_BEN_OWNER_TYP ADD OWNER_TYPE CHAR(1);

----- TEST DATA CHANGES ------
UPDATE LU_BEN_OWNER_TYP SET OWNER_TYPE = 'A';
INSERT INTO LU_BEN_OWNER_TYP(CODE, OWNER_TYPE, DESCRIPTION) VALUES ('05', 'P', 'Program Manager');
INSERT INTO LU_BEN_OWNER_TYP(CODE, OWNER_TYPE, DESCRIPTION) VALUES ('06', 'P', 'Managing Director');
UPDATE LU_BEN_OWNER_TYP SET OWNER_TYPE = 'P' WHERE DESCRIPTION IN ('Managing Employee', 'Board Member or Officer', 'Program Manager', 'Managing Director');
UPDATE LU_BEN_OWNER_TYP SET DESCRIPTION = 'Owner - 5% or more' WHERE CODE = '03';
-- not profit org owner types
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9901, '04', 'BeneficialOwnerType', '04', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9902, '04', 'BeneficialOwnerType', '02', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9903, '04', 'BeneficialOwnerType', '01', 'BT');
    
-- sole proprietorship owner types
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9904, '01', 'BeneficialOwnerType', '03', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9905, '01', 'BeneficialOwnerType', '02', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9906, '01', 'BeneficialOwnerType', '01', 'BT');
    
-- hospital based owner types
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9907, '05', 'BeneficialOwnerType', '04', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9908, '05', 'BeneficialOwnerType', '03', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9909, '05', 'BeneficialOwnerType', '02', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9910, '05', 'BeneficialOwnerType', '01', 'BT');
    
-- corporation owner types
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9911, '03', 'BeneficialOwnerType', '03', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9912, '03', 'BeneficialOwnerType', '02', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9912, '03', 'BeneficialOwnerType', '01', 'BT');
    
-- partnership
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9914, '02', 'BeneficialOwnerType', '03', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9915, '02', 'BeneficialOwnerType', '02', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9916, '02', 'BeneficialOwnerType', '01', 'BT');

-- state owned
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9917, '06', 'BeneficialOwnerType', '02', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9918, '06', 'BeneficialOwnerType', '01', 'BT');
    
-- public
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9919, '07', 'BeneficialOwnerType', '01', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9920, '07', 'BeneficialOwnerType', '05', 'BT');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (9921, '07', 'BeneficialOwnerType', '06', 'BT');
    
INSERT INTO AGREEMENT_DOCUMENT(AGREEMENT_DOCUMENT_ID, DOC_TYPE, TITLE, VERSION, DOC_TEXT, CREATED_BY, CREATE_TS)
    VALUES (3, '03', 'Child And Teen Checkup Agreement (DHS-4646)', 1, 'This is some text', 'SYSTEM', SYSDATE);
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (5401, '54', 'AgreementDocument', '03', 'RA');


-- added 2/26    
  CREATE TABLE "CMS"."LU_SVC_CAT" 
   (    "CODE" VARCHAR2(2 CHAR), 
    "DESCRIPTION" VARCHAR2(255 CHAR)
   ) ;
   
   ALTER TABLE "CMS"."LU_SVC_CAT" ADD PRIMARY KEY ("CODE") ENABLE;
    
   
     CREATE TABLE "CMS"."PROVIDER_SVCS" 
   (    "PROVIDER_SVCS_ID" NUMBER(19,0), 
    "PROFILE_ID" NUMBER(19,0),
    "TICKET_ID" NUMBER(19,0),
    "SVC_CAT_CD" VARCHAR2(2 CHAR)
   ) ;
   
   ALTER TABLE "CMS"."PROVIDER_SVCS" ADD PRIMARY KEY ("PROVIDER_SVCS_ID") ENABLE;

INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('CA', 'Adult Rehabilitative Mental Health Services');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('CB', 'Children''s Therapeutic Services and Supports (CTSS)');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('CC', 'Adult Crisis Response Services - Crisis Assessment &' || ' Crisis Intervention');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('CD', 'Adult Crisis Response Services - Crisis Stabilization');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('CE', 'Adult Crisis Response Services - Short-Term Residential');


INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('AN', 'Day Training &' || ' Habilitation License');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (5901, '59', 'LicenseType', 'AN', 'LO');

INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6101, '61', 'LicenseType', 'A1', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6102, '61', 'LicenseType', 'A2', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6103, '61', 'LicenseType', 'A3', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6104, '61', 'LicenseType', 'A4', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6105, '61', 'LicenseType', 'A5', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6106, '61', 'LicenseType', 'A6', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6107, '61', 'LicenseType', 'A7', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6108, '61', 'LicenseType', 'A8', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6109, '61', 'LicenseType', 'A9', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6110, '61', 'LicenseType', 'A0', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6111, '61', 'LicenseType', 'AA', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6112, '61', 'LicenseType', 'AB', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6113, '61', 'LicenseType', 'AC', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6114, '61', 'LicenseType', 'AD', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6115, '61', 'LicenseType', 'AE', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6116, '61', 'LicenseType', 'AF', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6117, '61', 'LicenseType', 'AG', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6118, '61', 'LicenseType', 'AH', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6119, '61', 'LicenseType', 'AI', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6120, '61', 'LicenseType', 'AJ', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6121, '61', 'LicenseType', 'AK', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6122, '61', 'LicenseType', 'AL', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6123, '61', 'LicenseType', 'AM', 'LO');

   
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('01', 'AC Transportation');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('02', 'Home Delivered Meals');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('03', 'Adult Day Services');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('04', 'Homemaker Services');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('05', 'Behavioral Program Services');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('06', 'In-home Family Support');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('07', 'Caregiver Training');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('08', 'Independent Living Skills');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('09', 'Case Management Waiver/Alternative Care');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('10', 'Modification and Adaptations');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('11', 'Chore');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('12', 'Nutritional Services');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('13', 'Cognitive Therapy');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('14', 'PERS and AC Supplies');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('15', 'Companion Services');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('16', 'Respite Care');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('17', 'Consumer Directed Community Support (CDCS)');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('18', 'Specialized Supplies &'|| ' Equipment (Waiver)');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('19', 'Spenddown Collection');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('20', 'Customized Living, 24 CL, Residential Care Services, Assisted Living Services');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('21', 'Structured Day Program Services');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('22', 'Supported Employment Services');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('23', 'Family Counseling and Training');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('24', 'Supported Living Services');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('25', 'Foster Care Services');
INSERT INTO LU_SVC_CAT(CODE, DESCRIPTION) VALUES ('26', 'Waiver Transportation');



ALTER TABLE CMS_ATTACHMENT MODIFY FILE_NAME VARCHAR(300);


-- for 3/7 release

CREATE TABLE "CMS"."LU_COUNTY" (    
    "CODE" VARCHAR2(2 CHAR), 
    "DESCRIPTION" VARCHAR2(255 CHAR)
);
ALTER TABLE "CMS"."LU_COUNTY" MODIFY ("CODE" NOT NULL ENABLE);
ALTER TABLE "CMS"."LU_COUNTY" ADD PRIMARY KEY ("CODE") ENABLE;

INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('01', 'Aitkin');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('02', 'Anoka');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('03', 'Becker');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('04', 'Beltrami');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('05', 'Benton');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('06', 'Big Stone');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('07', 'Blue Earth');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('08', 'Brown');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('09', 'Carlton');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('10', 'Carver');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('11', 'Cass');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('12', 'Chippewa');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('13', 'Chisago');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('14', 'Clay');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('15', 'Clearwater');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('16', 'Cook');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('17', 'Cottonwood');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('18', 'Crow Wing');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('19', 'Dakota');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('20', 'Dodge');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('21', 'Douglas');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('22', 'Faribault');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('23', 'Fillmore');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('24', 'Freeborn');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('25', 'Goodhue');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('26', 'Grant');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('27', 'Hennepin');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('28', 'Houston');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('29', 'Hubbard');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('30', 'Isanti');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('31', 'Itasca');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('32', 'Jackson');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('33', 'Kanabec');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('34', 'Kandiyohi');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('35', 'Kittson');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('36', 'Koochiching');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('37', 'Lac qui Parle');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('38', 'Lake');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('39', 'Lake of the Woods');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('40', 'Le Sueur');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('41', 'Lincoln');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('42', 'Lyon');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('43', 'Mahnomen');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('44', 'Marshall');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('45', 'Martin');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('46', 'McLeod');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('47', 'Meeker');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('48', 'Mille Lacs');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('49', 'Morrison');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('50', 'Mower');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('51', 'Murray');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('52', 'Nicollet');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('53', 'Nobles');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('54', 'Norman');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('55', 'Olmsted');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('56', 'Otter Tail');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('57', 'Pennington');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('58', 'Pine');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('59', 'Pipestone');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('60', 'Polk');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('61', 'Pope');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('62', 'Ramsey');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('63', 'Red Lake');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('64', 'Redwood');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('65', 'Renville');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('66', 'Rice');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('67', 'Rock');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('68', 'Roseau');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('69', 'Scott');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('70', 'Sherburne');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('71', 'Sibley');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('72', 'St. Louis');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('73', 'Stearns');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('74', 'Steele');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('75', 'Stevens');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('76', 'Swift');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('77', 'Todd');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('78', 'Traverse');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('79', 'Wabasha');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('80', 'Wadena');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('81', 'Waseca');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('82', 'Washington');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('83', 'Watonwan');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('84', 'Wilkin');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('85', 'Winona');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('86', 'Wright');
INSERT INTO LU_COUNTY(CODE, DESCRIPTION) VALUES ('87', 'Yellow');

    
INSERT INTO LU_PROVIDER_TYPE(CODE, APPLICANT_TYP, DESCRIPTION, PRIVATE_OFFICE_FLG, EMPLOYED_CONTRACTED_FLG, ADDITONAL_PRACTICE_FLG, PAYMENT_REQUIRED_FLG, AGREEMENT_FLG, ADDENDUM_FLG) VALUES ('64', 1, 'Individual Education Plan', 'N', 'N', 'N', 'N', 'N', 'N');
INSERT INTO LU_PROVIDER_TYPE(CODE, APPLICANT_TYP, DESCRIPTION, PRIVATE_OFFICE_FLG, EMPLOYED_CONTRACTED_FLG, ADDITONAL_PRACTICE_FLG, PAYMENT_REQUIRED_FLG, AGREEMENT_FLG, ADDENDUM_FLG) VALUES ('65', 1, 'Nursing Facility', 'N', 'N', 'N', 'N', 'N', 'N');

INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('AO', 'License and Transmittal (CMS 1539 Form) from MN Department of Health');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('AP', 'Approval by Kent Dufresne to enroll new facility');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6501, '65', 'LicenseType', 'AO', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6502, '65', 'LicenseType', 'AP', 'LO');


    
    
ALTER TABLE PROVIDER_PROFILE MODIFY COUNTY_NAME VARCHAR(200);
ALTER TABLE PROVIDER_PROFILE ADD PREV_MEDICARE_NUMBER VARCHAR(50);
ALTER TABLE PROVIDER_PROFILE ADD TITLE_18_BED_COUNT NUMBER(*,0);
ALTER TABLE PROVIDER_PROFILE ADD TITLE_19_BED_COUNT NUMBER(*,0);
ALTER TABLE PROVIDER_PROFILE ADD DUAL_CERT_BED_COUNT NUMBER(*,0);
ALTER TABLE PROVIDER_PROFILE ADD ICF_BED_COUNT NUMBER(*,0);
ALTER TABLE PROVIDER_PROFILE ADD PT_OT_IND CHAR(1 BYTE);


INSERT INTO LU_PROVIDER_TYPE(CODE, APPLICANT_TYP, DESCRIPTION, PRIVATE_OFFICE_FLG, EMPLOYED_CONTRACTED_FLG, ADDITONAL_PRACTICE_FLG, PAYMENT_REQUIRED_FLG, AGREEMENT_FLG, ADDENDUM_FLG) VALUES ('66', 1, 'Hospice', 'N', 'N', 'N', 'N', 'N', 'N');

INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('AQ', 'Hospice license from the MN Dept of Health');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('AR', 'CMS Medicare Certification Letter');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('AS', 'Ambulance Services - Basic Service');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('AT', 'Ambulance Services - Advanced Life Support');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('AU', 'Ambulance Services - Air Transport with FAA Air Worthiness Certificate');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6601, '66', 'LicenseType', 'AQ', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6602, '66', 'LicenseType', 'AR', 'LO');
            

INSERT INTO LU_PROVIDER_TYPE(CODE, APPLICANT_TYP, DESCRIPTION, PRIVATE_OFFICE_FLG, EMPLOYED_CONTRACTED_FLG, ADDITONAL_PRACTICE_FLG, PAYMENT_REQUIRED_FLG, AGREEMENT_FLG, ADDENDUM_FLG) VALUES ('67', 1, 'Hospital', 'N', 'N', 'N', 'N', 'N', 'N');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('AV', 'State License to operate as a Hospital');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('AW', 'CMS PECOS Website Verification');
INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('AX', 'CLIA Certificate if billing Lab Services');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6701, '67', 'LicenseType', 'AV', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6702, '67', 'LicenseType', 'AR', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6703, '67', 'LicenseType', 'AW', 'LO');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (6704, '67', 'LicenseType', 'AX', 'LO');


