INSERT INTO LU_LICENSE_TYPE(CODE, DESCRIPTION) VALUES ('Q3', 'Licensed Practical Nurse');

INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (1503, '15', 'LicenseType', 'Q3', 'LO');