INSERT INTO lu_issuing_board(code, description) VALUES ('C5', 'ABOMS');
INSERT INTO PROVIDER_SETTING(PROVIDER_SETTING_ID, PROVIDER_TYP_CD, RELATED_ENTITY_TYP, RELATED_ENTITY_CD, REL_TYP)
    VALUES (2110, '21', 'IssuingBoard', 'C5', 'SB');