  CREATE TABLE "CMS"."LEGACY_MAPPING"
   (	"LEGACY_MAPPING_ID" NUMBER(19,0),
	"SYSTEM_NM" VARCHAR2(200 CHAR),
	"CODE_TYPE" VARCHAR2(200 CHAR),
	"INTERNAL_CODE" VARCHAR2(200 CHAR),
	"EXTERNAL_CODE" VARCHAR2(200 CHAR)
   ) ;

  ALTER TABLE "CMS"."LEGACY_MAPPING" ADD PRIMARY KEY ("LEGACY_MAPPING_ID") ENABLE;
  ALTER TABLE ENTITY add LEGACY_ID VARCHAR(9);