/*
 * Copyright (C) 2012 TopCoder Inc., All Rights Reserved.
 *
 * @author TCSASSEMBLER
 * @version 1.0
 * @since External Sources Integration Assembly II
 */
package cms.externalsources

import gov.medicaid.domain.model.*
import gov.medicaid.domain.rules.inference.*

global gov.medicaid.services.CMSConfigurator appConfig;

rule 'Birth Center Accreditation external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(licenseType == LicenseNames.BIRTH_CENTER_ACCREDITATION.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher(true)); // discard non matches for this service type
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/AccreditedBirthCentersLicenseService");
        $config.setRequestTranslationFile("/xslt/accredited_birth_center_req.xsl");
        $config.setResponseTranslationFile("/xslt/accredited_birth_center_res.xsl");
end

rule 'LPCC external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.PROFESSIONAL_CLINICAL_COUNSELOR.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so match only the name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/BBHTLicenseService");
        $config.setRequestTranslationFile("/xslt/bbht_req.xsl");
        $config.setResponseTranslationFile("/xslt/bbht_res.xsl");
end

rule 'LPCI external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.PROFESSIONAL_COUNSELOR_INDEPENDENT.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so match only the name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/BBHTLicenseService");
        $config.setRequestTranslationFile("/xslt/bbht_req.xsl");
        $config.setResponseTranslationFile("/xslt/bbht_res.xsl");
end

rule 'LADC external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.ALCOHOL_AND_DRUG_COUNSELOR.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so match only the name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/BBHTLicenseService");
        $config.setRequestTranslationFile("/xslt/bbht_req.xsl");
        $config.setResponseTranslationFile("/xslt/bbht_res.xsl");
end

rule 'CDT external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.CHEMICAL_DEPENDENCY_TREATMENT.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so match only the name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/ChemicalDependencyProgramService");
        $config.setRequestTranslationFile("/xslt/org_dhs_licensing_req.xsl");
        $config.setResponseTranslationFile("/xslt/org_dhs_licensing_res.xsl");
end

rule 'CRF external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.CHILDREN_S_RESIDENTIAL_FACILITIES.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so match only the name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/ChildrensResidentialService");
        $config.setRequestTranslationFile("/xslt/org_dhs_licensing_req.xsl");
        $config.setResponseTranslationFile("/xslt/org_dhs_licensing_res.xsl");
end

rule 'Chiropractic external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.CHIROPRACTIC_EXAMINER.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new NameAndNumberMatcher()); // search by last name only so do name and license number filtering
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/ChiropracticLicenseService");
        $config.setRequestTranslationFile("/xslt/chiropractic_req.xsl");
        $config.setResponseTranslationFile("/xslt/chiropractic_res.xsl");
end

rule 'CMHC external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.MEDICARE_CERTIFICATION_COMMUNITY_MENTAL_HEALTH_CLINIC.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/CommunityMentalHealthCenterLicensingService");
        $config.setRequestTranslationFile("/xslt/org_healthcare_licensing_req.xsl");
        $config.setResponseTranslationFile("/xslt/org_healthcare_licensing_res.xsl");
end

rule 'DTHS external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.DAY_TRAINING_HABILITATION_LICENSE.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so match only the name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/DayTrainingAndHabilitationCenterService");
        $config.setRequestTranslationFile("/xslt/org_dhs_licensing_req.xsl");
        $config.setResponseTranslationFile("/xslt/org_dhs_licensing_res.xsl");
end

rule 'DNP external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.DIETICIAN_OR_NUTRITIONIST.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so match only the name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/DieteticsAndNutritionPracticeLicenseService");
        $config.setRequestTranslationFile("/xslt/dnp_req.xsl");
        $config.setResponseTranslationFile("/xslt/dnp_res.xsl");
end

rule 'OT external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.OCCUPATIONAL_THERAPY.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new NameAndTypeMatcher()); // search can return multiple license types for the number
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/HealthOccupationsProgramCredentialService");
        $config.setRequestTranslationFile("/xslt/hopc_req.xsl");
        $config.setResponseTranslationFile("/xslt/hopc_res.xsl");
end

rule 'SLP external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.SPEECH_LANGUAGE_PATHOLOGIST.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new NameAndTypeMatcher()); // search can return multiple license types for the number
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/HealthOccupationsProgramCredentialService");
        $config.setRequestTranslationFile("/xslt/hopc_req.xsl");
        $config.setResponseTranslationFile("/xslt/hopc_res.xsl");
end

rule 'AUD external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.AUDIOLOGIST.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new NameAndTypeMatcher()); // search can return multiple license types for the number
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/HealthOccupationsProgramCredentialService");
        $config.setRequestTranslationFile("/xslt/hopc_req.xsl");
        $config.setResponseTranslationFile("/xslt/hopc_res.xsl");
end

rule 'HID external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.HEARING_AID_DISPENSER.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new NameAndTypeMatcher()); // search can return multiple license types for the number
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/HealthOccupationsProgramCredentialService");
        $config.setRequestTranslationFile("/xslt/hopc_req.xsl");
        $config.setResponseTranslationFile("/xslt/hopc_res.xsl");
end

rule 'AUDSLP external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.DUAL_AUDIOLOGIST_AND_SPEECH_LANGUAGE_PATHOLOGIST.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new NameAndTypeMatcher()); // search can return multiple license types for the number
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/HealthOccupationsProgramCredentialService");
        $config.setRequestTranslationFile("/xslt/hopc_req.xsl");
        $config.setResponseTranslationFile("/xslt/hopc_res.xsl");
end

rule 'HOSPICE external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.MEDICARE_CERTIFIED_HOSPICE.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/HospiceLicensingService");
        $config.setRequestTranslationFile("/xslt/org_healthcare_licensing_req.xsl");
        $config.setResponseTranslationFile("/xslt/org_healthcare_licensing_res.xsl");
end

rule 'HOSPITAL external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.CERTIFIED_HOSPITAL.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/HospitalLicensingService");
        $config.setRequestTranslationFile("/xslt/org_healthcare_licensing_req.xsl");
        $config.setResponseTranslationFile("/xslt/org_healthcare_licensing_res.xsl");
end

rule 'IRTS external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.INTENSIVE_RESIDENTIAL_TREATMENT_SERVICES.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so match only the name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/IntensiveResidentialTreatmentServiceService");
        $config.setRequestTranslationFile("/xslt/org_dhs_licensing_req.xsl");
        $config.setResponseTranslationFile("/xslt/org_dhs_licensing_res.xsl");
end

rule 'MFT external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.MARRIAGE_AND_FAMILY_THERAPIST.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so match only the name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/MarriageAndFamilyTherapyLicenseService");
        $config.setRequestTranslationFile("/xslt/mft_req.xsl");
        $config.setResponseTranslationFile("/xslt/mft_res.xsl");
end

rule 'Medical Practice external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.PHYSICIAN.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so filter by name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/MedicalPracticeLicenseService");
        $config.setRequestTranslationFile("/xslt/physician_req.xsl");
        $config.setResponseTranslationFile("/xslt/physician_res.xsl");
end

rule 'CRNA specialty external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(specialtyType == LicenseNames.CERTIFIED_REGISTERED_NURSE_ANESTHETIST.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so filter by name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/NurseAnesthetistsLicenseService");
        $config.setRequestTranslationFile("/xslt/crna_req.xsl");
        $config.setResponseTranslationFile("/xslt/crna_res.xsl");
end

rule 'RN license external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.REGISTERED_NURSE.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so filter by name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/NursingLicenseService");
        $config.setRequestTranslationFile("/xslt/registered_nurse_req.xsl");
        $config.setResponseTranslationFile("/xslt/registered_nurse_res.xsl");
end

rule 'Optometrist license external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.OPTOMETRIST.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so filter by name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/OptometryLicenseService");
        $config.setRequestTranslationFile("/xslt/mft_req.xsl");
        $config.setResponseTranslationFile("/xslt/mft_res.xsl");
end

rule 'RS ICF DD external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.RESIDENTIAL_SERVICES_ICF_DD.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so match only the name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/PersonsWithDevelopmentalDisabilitiesIntermediateCareFacilityService");
        $config.setRequestTranslationFile("/xslt/org_dhs_licensing_req.xsl");
        $config.setResponseTranslationFile("/xslt/org_dhs_licensing_res.xsl");
end

rule 'Pharmacist license external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.PHARMACIST_LICENSE.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new NameAndTypeMatcher()); //  multiple license types returned so filter by type too
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/PharmacyLicenseService");
        $config.setRequestTranslationFile("/xslt/pharmacist_req.xsl");
        $config.setResponseTranslationFile("/xslt/pharmacist_res.xsl");
end

rule 'PT license external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.PHYSICAL_THERAPIST.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so filter by name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/PhysicalTherapyLicenseService");
        $config.setRequestTranslationFile("/xslt/mft_req.xsl");
        $config.setResponseTranslationFile("/xslt/mft_res.xsl");
end

rule 'Podiatrist license external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(issuingState == "MN", licenseType == LicenseNames.PODIATRIST_LICENSE.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so filter by name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/PodiatricMedicineLicenseService");
        $config.setRequestTranslationFile("/xslt/podiatrist_req.xsl");
        $config.setResponseTranslationFile("/xslt/podiatrist_res.xsl");
end

rule 'ESRD external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(licenseType == LicenseNames.END_STAGE_RENAL_DIALYSIS.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); 
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/RenalDialysisFreeStandingLicensingService");
        $config.setRequestTranslationFile("/xslt/org_healthcare_licensing_req.xsl");
        $config.setResponseTranslationFile("/xslt/org_healthcare_licensing_res.xsl");
end

rule 'CSW external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(licenseType == LicenseNames.CLINICAL_SOCIAL_WORKER.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ProviderNameMatcher()); // search by license number so match only the name
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/SocialWorkLicenseService");
        $config.setRequestTranslationFile("/xslt/podiatrist_req.xsl");
        $config.setResponseTranslationFile("/xslt/sw_res.xsl");
end

rule 'Class A License external source configuration for the current environment'
dialect 'mvel'
    when
        $config : LicenseLookupConfiguration(licenseType == LicenseNames.CLASS_A_PROFESSIONAL_HOME_CARE_LICENSE.value()) 
    then
        $config.setLookupSupported("Y");
        $config.setMatcher(new ClassificationMatcher()); // search by name, filter by classification
        $config.setServiceEndPoint(appConfig.getExternalSourceBase() +  "/cms-ext/ws/PublicHealthNursingOrganizationLicensingService");
        $config.setRequestTranslationFile("/xslt/org_healthcare_licensing_req.xsl");
        $config.setResponseTranslationFile("/xslt/org_healthcare_licensing_res.xsl");
end
