#!/bin/sh

OUTPUT_FORMAT="${1}"

if [ "${1}" != "human" -a "${1}" != "elisp" ]; then
  echo 'Must pass "human" or "elisp" argument to indicate output format.'
  exit 1
fi

if [ "${OUTPUT_FORMAT}" = "elisp" ]; then 
  echo "("
fi

./reqs2any --output="${OUTPUT_FORMAT}" \
   csv-exports/reqs-fr.csv             \
   csv-exports/reqs-ii.csv             \
   csv-exports/reqs-sc.csv             \
   csv-exports/reqs-ia.csv             \
   csv-exports/reqs-iu.csv             \
   csv-exports/reqs-ad.csv             \
   csv-exports/reqs-sq.csv             \
   csv-exports/reqs-ph.csv

if [ "${OUTPUT_FORMAT}" = "elisp" ]; then 
  echo ")"
fi
